### ISSUE TITLE
listing-5.11.html: how is "Starting at" text made uppercase?

### ISSUE THREAD

**Issue by space88man** [CSSInDepth/css-in-depth#5]
After loading listing-5.11.html the text "Starting at" in the <small> element is in regular case.

The image in Chapter 5.1 shows it as all uppercase: "STARTING AT"

**Comment by space88man** [comment]
C.f. Figure 6.9 which shows it as "Starting at"

**Comment by mhorskaya** [comment]
Color is also a bit off.

Adding these lines did the trick.

```css
.centered > small {
    text-transform: uppercase;
    color: #5f4b44;
}
```
